apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataintelligence.fullname" . }}
  labels:
    {{- include "dataintelligence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dataintelligence.selectorLabels" . | nindent 4 }}
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
    - name: mcp
      port: {{ .Values.service.mcpPort }}
      targetPort: mcp
